kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  namespace: golang-cicd
  labels:
    app: golang-gitwebhook-interface
    app.kubernetes.io/component: golang-gitwebhook-interface
    app.kubernetes.io/instance: golang-gitwebhook-interface
    name: golang-gitwebhook-interface
  name: golang-gitwebhook-interface

spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  revisionHistoryLimit: 10

  selector:
    matchLabels:
      app.kubernetes.io: golang-gitwebhook-interface
  template:
    metadata:
      labels:
        app.kubernetes.io: golang-gitwebhook-interface
        name: golang-gitwebhook-interface
    spec:
      containers:
        - resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
          readinessProbe:
            httpGet:
              path: /isalive
              port: 9000
              scheme: HTTP
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 1
          terminationMessagePath: /dev/termination-log
          name: golang-gitwebhook-interface
          livenessProbe:
            httpGet:
              path: /isalive
              port: 9000
              scheme: HTTP
            initialDelaySeconds: 55
            timeoutSeconds: 5
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 2
          env:
            - name: LOG_LEVEL
              value: trace
            - name: VERSION
              value: 1.0.1
            - name: SERVER_PORT
              value: '9000'
            - name: WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: webhook-secret
                  key: api-key
            - name: NAME
              value: golang-gitwebhook-interface
            - name: URL_DEV
              value: 'http://el-eventlistener-dev.golang-cicd.svc.cluster.local:8080'
            - name: URL_UAT
              value: 'http://el-eventlistener-dev.golang-cicd.svc.cluster.local:8080'
            - name: URL_PROD
              value: 'http://el-eventlistener-dev.golang-cicd.svc.cluster.local:8080'
            - name: REPO_MAPPING
              valueFrom:
                configMapKeyRef:
                  name: infra-mapping
                  key: repo
          ports:
            - containerPort: 9000
              protocol: TCP
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: >-
            quay.io/luigizuccarelli/golang-gitwebhook-interface:1.15.6
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}


