apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: golang-sonarqube-dev
spec:
  params:
  - name: message
    description: The message to print
    default: This is the default message
    type: string
  - name: repo-name
    description: The name of the repo
    type: string
  - name: repo-url
    description: The url of the repo
    type: string
  - name: repo-hash
    description: The commit hash of the repo
    type: string
  - name: actor-name
    description: The actor
    type: string
  - name: actor-email
    description: The actors email
    type: string
  - name: SONAR_HOST_URL
    description: SonarQube host
    type: string
  - name: SONAR_PROJECT_KEY
    description: The project key
    type: string
  - name: SONAR_SECRET
    description: Sonarqube access token
    type: string
    
  workspaces:
    - name: output
       
  steps: 
  - name: info
    image: bash
    command: ["bash", "-c"]
    args: ["echo -e 'Pipeline run project : $(params.repo-name)\ncommit hash :  $(params.repo-hash)\nuser info : $(params.actor-name) : $(params.actor-email)\nsonarqube url : $(params.SONAR_HOST_URL)'"]
    
  - name: sonar-properties-create
    image: registry.access.redhat.com/ubi8/ubi-minimal:latest
    workingDir: /workspace/output/$(params.repo-name)
    env:
    - name: SONAR_TOKEN
      valueFrom:
        secretKeyRef:
          name: $(params.SONAR_SECRET)
          key: token    
     
    script: |
      #!/usr/bin/env bash
        
      touch sonar-project.properties
      echo "sonar.login=$SONAR_TOKEN" >> sonar-project.properties
      echo "sonar.projectKey=$(params.SONAR_PROJECT_KEY)" >> sonar-project.properties
      echo "sonar.host.url=$(params.SONAR_HOST_URL)" >> sonar-project.properties

      echo "---------------------------"
      cat sonar-project.properties

  - name: sonar-scan
    image: sonarsource/sonar-scanner-cli
    workingDir: /workspace/output/$(params.repo-name)
    
    script: |
      #!/usr/bin/env bash

      sonar-scanner 
      echo $? 
  - name: sonar-quality-gate
    image:  dwdraju/alpine-curl-jq
    workingDir: /workspace/output/$(params.repo-name)
    env:
    - name: SONAR_TOKEN
      valueFrom:
        secretKeyRef:
          name: $(params.SONAR_SECRET)
          key: token
    script: |
      #!/usr/bin/env bash

      uri=$(params.SONAR_HOST_URL)/api/qualitygates/project_status?projectKey=$(params.SONAR_PROJECT_KEY)
      echo -e "$SONAR_TOKEN: $uri\n"
      status=$(curl -s -u "$SONAR_TOKEN:" -H 'Content-Type: application/json' -H 'Accept: application/json'  "$uri" | jq '.projectStatus.status')
      echo -e "status check:$status:\n"
      # check to see if the job was succesful
      if [ "$status" != "\"OK\"" ];
      then
        echo -e "SONARQUBE SCAN FAILED!\n"
        exit 1
      else
        echo -e "SONARQUBE SCAN PASSED!\n"
        exit 0
      fi
 
