apiVersion: v1
kind: Secret
metadata:
  name: argocd-git-basic
  annotations:
    tekton.dev/git-0: http://lmzsoftware.com/ 
type: Opaque
data:
  username: cm9ib3QtY2ljZAo= 
  password: cm9ib3QtY2ljZDAxCg==
