apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

  
resources:
  - namespace/namespace.yaml
  - namespace/limit-range.yaml
  - namespace/resource-quota.yaml
  - shared/pipeline-pvc.yaml
 
namespace: golang-cicd

