kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: build-cache-pvc-dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-storage 
  resources:
    requests:
      storage: 2Gi
