kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pipeline-pvc-dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage 
  resources:
    requests:
      storage: 5Gi
